version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=next-reddit
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  dbdata:
